import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
  /**
   * https://developer.android.com/jetpack/androidx
   */
  const val androidx_appcompat_appcompat: String = "androidx.appcompat:appcompat:" +
      Versions.androidx_appcompat_appcompat

  /**
   * http://tools.android.com
   */
  const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:" +
      Versions.constraintlayout

  /**
   * https://developer.android.com/jetpack/androidx
   */
  const val core_ktx: String = "androidx.core:core-ktx:" + Versions.core_ktx

  /**
   * http://developer.android.com/tools/extras/support-library.html
   */
  const val legacy_support_v4: String = "androidx.legacy:legacy-support-v4:" +
      Versions.legacy_support_v4

  const val multidex: String = "androidx.multidex:multidex:" + Versions.multidex

  /**
   * https://github.com/aliyun/aliyun-oss-android-sdk
   */
  const val oss_android_sdk: String = "com.aliyun.dpa:oss-android-sdk:" + Versions.oss_android_sdk

  /**
   * https://developer.android.com/studio
   */
  const val aapt2: String = "com.android.tools.build:aapt2:" + Versions.aapt2

  /**
   * https://developer.android.com/studio
   */
  const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
      Versions.com_android_tools_build_gradle

  /**
   * https://developer.android.com/studio
   */
  const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

  /**
   * https://github.com/dcendents/android-maven-gradle-plugin
   */
  const val android_maven_gradle_plugin: String =
      "com.github.dcendents:android-maven-gradle-plugin:" + Versions.android_maven_gradle_plugin

  /**
   * https://github.com/JakeWharton/RxBinding/
   */
  const val rxbinding: String = "com.jakewharton.rxbinding:rxbinding:" + Versions.rxbinding

  /**
   * https://github.com/rengwuxian/MaterialEditText
   */
  const val library: String = "com.rengwuxian.materialedittext:library:" + Versions.library

  /**
   * https://square.github.io/okhttp/
   */
  const val logging_interceptor: String = "com.squareup.okhttp3:logging-interceptor:" +
      Versions.com_squareup_okhttp3

  /**
   * https://square.github.io/okhttp/
   */
  const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.com_squareup_okhttp3

  /**
   * https://github.com/square/picasso/
   */
  const val picasso: String = "com.squareup.picasso:picasso:" + Versions.picasso

  /**
   * https://github.com/square/retrofit
   */
  const val adapter_rxjava: String = "com.squareup.retrofit2:adapter-rxjava:" +
      Versions.com_squareup_retrofit2

  /**
   * https://github.com/square/retrofit
   */
  const val converter_gson: String = "com.squareup.retrofit2:converter-gson:" +
      Versions.com_squareup_retrofit2

  /**
   * https://github.com/square/retrofit
   */
  const val converter_simplexml: String = "com.squareup.retrofit2:converter-simplexml:" +
      Versions.com_squareup_retrofit2

  /**
   * https://github.com/square/retrofit
   */
  const val retrofit: String = "com.squareup.retrofit2:retrofit:" + Versions.com_squareup_retrofit2

  /**
   * https://github.com/yqritc/RecyclerView-FlexibleDivider
   */
  const val recyclerview_flexibledivider: String = "com.yqritc:recyclerview-flexibledivider:" +
      Versions.recyclerview_flexibledivider

  const val de_fayard_buildsrcversions_gradle_plugin: String =
      "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
      Versions.de_fayard_buildsrcversions_gradle_plugin

  /**
   * https://github.com/ReactiveX/RxAndroid
   */
  const val rxandroid: String = "io.reactivex:rxandroid:" + Versions.io_reactivex

  /**
   * https://github.com/ReactiveX/RxJava
   */
  const val rxjava: String = "io.reactivex:rxjava:" + Versions.io_reactivex

  /**
   * https://github.com/JetBrains/anko
   */
  const val anko_appcompat_v7: String = "org.jetbrains.anko:anko-appcompat-v7:" +
      Versions.org_jetbrains_anko

  /**
   * https://github.com/JetBrains/anko
   */
  const val anko_common: String = "org.jetbrains.anko:anko-common:" + Versions.org_jetbrains_anko

  /**
   * https://github.com/JetBrains/anko
   */
  const val anko_recyclerview_v7: String = "org.jetbrains.anko:anko-recyclerview-v7:" +
      Versions.org_jetbrains_anko

  /**
   * https://github.com/JetBrains/anko
   */
  const val anko_sdk15: String = "org.jetbrains.anko:anko-sdk15:" + Versions.org_jetbrains_anko

  /**
   * https://github.com/JetBrains/anko
   */
  const val anko_support_v4: String = "org.jetbrains.anko:anko-support-v4:" +
      Versions.org_jetbrains_anko

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions_runtime: String =
      "org.jetbrains.kotlin:kotlin-android-extensions-runtime:" +
      Versions.kotlin_android_extensions_runtime

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_android_extensions: String = "org.jetbrains.kotlin:kotlin-android-extensions:" +
      Versions.kotlin_android_extensions

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:" +
      Versions.kotlin_gradle_plugin

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:" +
      Versions.kotlin_reflect

  /**
   * https://kotlinlang.org/
   */
  const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" + Versions.kotlin_stdlib

  /**
   * http://github.com/ligboy/retrofit-converters
   */
  const val converter_fastjson_android: String =
      "org.ligboy.retrofit2:converter-fastjson-android:" + Versions.converter_fastjson_android
}
