import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
  const val androidx_appcompat_appcompat: String = "1.2.0"

  const val constraintlayout: String = "2.0.4"

  const val core_ktx: String = "1.3.2"

  const val legacy_support_v4: String = "1.0.0"

  const val multidex: String = "2.0.0" // available: "2.0.1"

  const val oss_android_sdk: String = "2.4.5" // available: "2.9.5"

  const val aapt2: String = "4.0.0-6051327" // available: "4.1.2-6503028"

  const val com_android_tools_build_gradle: String = "4.0.0" // available: "4.1.2"

  const val lint_gradle: String = "27.0.0" // available: "27.1.2"

  const val android_maven_gradle_plugin: String = "1.5" // available: "2.1"

  const val rxbinding: String = "0.4.0" // available: "1.0.1"

  const val library: String = "2.1.4"

  const val com_squareup_okhttp3: String = "3.8.1" // available: "4.9.0"

  const val picasso: String = "2.5.2" // available: "2.71828"

  const val com_squareup_retrofit2: String = "2.1.0" // available: "2.9.0"

  const val recyclerview_flexibledivider: String = "1.4.0"

  const val de_fayard_buildsrcversions_gradle_plugin: String = "0.4.1" // available: "0.7.0"

  const val io_reactivex: String = "1.2.1"

  const val org_jetbrains_anko: String = "0.10.8"

  const val kotlin_android_extensions_runtime: String = "1.3.72" // available: "1.4.21-2"

  const val kotlin_android_extensions: String = "1.3.72" // available: "1.4.21-2"

  const val kotlin_gradle_plugin: String = "1.3.72" // available: "1.4.21-2"

  const val kotlin_reflect: String = "1.3.31" // available: "1.4.21-2"

  const val kotlin_stdlib: String = "1.3.72" // available: "1.4.21-2"

  const val converter_fastjson_android: String = "2.1.0" // available: "2.2.0"

  /**
   *
   * See issue 19: How to update Gradle itself?
   * https://github.com/jmfayard/buildSrcVersions/issues/19
   */
  const val gradleLatestVersion: String = "6.8"

  const val gradleCurrentVersion: String = "6.1.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
  inline get() =
      id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
